export const storeProducts =[
    {
        id: 1,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 2,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 3,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 7,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 8,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 9,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 10,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 11,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 12,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 13,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 14,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 15,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },    {
        id: 16,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 17,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 18,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 19,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 20,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 21,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 22,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 23,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 24,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 25,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 26,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 27,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 28,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 29,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 30,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 31,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 32,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 33,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 34,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 35,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },    {
        id: 36,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 37,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 38,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 39,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 40,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 41,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 42,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 43,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 44,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 45,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 46,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 47,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 48,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 49,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 50,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 51,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 52,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 53,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 54,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 55,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 56,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 57,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 58,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 59,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 60,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    },
    {
        id: 61,
        title: "Gooqle Pixel",
        img: "img/1.png",
        price: 10,
        company: "GOOGLE",
        info:"Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenjuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorialhella blue bottle. Tote baa wolf authentictry-hard put a bird on it mumblecore. UnicornLumbersexual master cleanse blog hella VHSvaporware sartorial church-key cardigan single-oriqin coffee Lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
        Cart: false, 
        count: 0, 
        total: 0
    },{
        id: 62,
        title: "Samsung S7",
        img: "img/1.png",
        price: 16,
        company: "SAMSUNG",
        info:'Lorem ipsum dolor amet offal butcher quinoasustainable gastropub, echo park actually greenuice sriracha paleo. Brooklyn sriracha semiotics,DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic',
        Cart: false,
        count : 0,
        total : 0
    },
    {
        id: 63,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 64,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 65,
        title: "Iphone 7",
        img: "img/1.png",
        price: 30,
        company: "apple",
        info:"Lorem ipsun dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha peleo.Brooklyn sriracha semiotics, DTY coloring book mixtape craft beer sarterial hella blue bottle. Tote bag wotf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse bLog hella VHS, vaporware sartorial church-key cardigan single-origin coffee 1o-fi organic asymmetrical.Taxidermy semiatics celiac stumgtown scenester normcore, ethical helvetica photo baoth gentrify.", 
        inCart: true,
        count: 0,
        total: 0
    }
];

export const detailProduct = {
    id: 1,
    title: "Google Pixel",
    img: "img/1.png",
    price: 10,
    company: "google",
    info:"Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo.Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn Lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical.Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false, 
    count: 0, 
    total: 0
};